name: 1.$(Date:yyMM).$(Rev:r)
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '17.x'
  displayName: 'Install Node.js'
- task: VersionJSONFile@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    recursion: True
    VersionNumber: '$(Build.BuildNumber)'
    useBuildNumberDirectly: False
    VersionRegex: '\d+\.\d+\.\d+'
    versionForJSONFileFormat: '{1}.{2}.{3}'
    FilenamePattern: 'package.json'
    OutputVersion: 'OutputedVersion'
  displayName: 'Bumping package version'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
  displayName: 'npm install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: 'npm run build'
- task: Npm@1
  displayName: 'Publishing NPM package'
  inputs:
    command: 'publish'
    workingDir: '$(Build.SourcesDirectory)'
    publishEndpoint: 'NPM - networg-npm'




