/* import { getRandomFile, getRandomImage } from "./faker"; */

let guids: any;

const getGuids = () => {
    const result: string[] = [];
    for (let i = 0; i < 15; i++) {
        result.push(window.crypto.randomUUID());
    }
    return result;
}


/* const getFiles = () => {
    const files = [];
    for (let i = 0; i < 15; i++) {
        files.push(getRandomFile())
    }
    return files;
}
const getImages = () => {
    const images = [];
    for (let i = 0; i < 15; i++) {
        images.push(getRandomImage())
    }
    return images;
} */

export const getDemoData = () => {
    if(!guids) {
        guids = getGuids();
        //files = getFiles();
        //images = getImages();
    }
    const data = [
        {
            "text": "Alice",
            "id": "alice.jones@company.com",
            "phone": "720453674",
            "url": "https://www.example.com",
            "number": 0,
            "decimal": 54321.123,
            "dateonly": "2024-10-05",
            "datetime": "2023-01-15T08:45:30",
            "duration": 8000,
            "currency": 450000,
            "_lookup_value": guids[1],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'Alice Lookup',
            "optionset": 2,
            "optionsetcolorful": 2,
            "multiselectoptionset": "1",
            "multiselectoptionsetcolorful": "1",
            "multilinetext": "Alice is a senior project manager with expertise in tech solutions.",
            "twooptions": true,
            "twooptionscolorful": 1,
            /* "file": guids[1],
            "file.filename": files[1].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[1].mimeType,
            "file.fileurl": files[1].fileUrl,
            'image': guids[1],
            "image.filename": images[1].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[1].imageMimeType,
            "image.fileurl": images[1].imageFileUrl,
            "image.thumbnailurl": images[1].imageThumbnailUrl */
        },
        {
            "text": "Michael",
            "id": "michael.smith@domain.com",
            "phone": "720998765",
            "url": "https://www.mysite.com",
            "number": 6543210,
            "decimal": 123456.789,
            "dateonly": "2022-03-10",
            "datetime": "2022-03-10T14:25:00",
            "duration": 12000,
            "currency": 800000,
            "_lookup_value": guids[2],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'Michael Lookup',
            "optionset": 1,
            "optionsetcolorful": 1,
            "multiselectoptionset": "2",
            "multiselectoptionsetcolorful": "2",
            "multilinetext": "Michael specializes in business consulting and process automation.",
            "twooptions": false,
            "twooptionscolorful": 0,
            /* "file": guids[2],
            "file.filename": files[2].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[2].mimeType,
            "file.fileurl": files[2].fileUrl,
            'image': guids[2],
            "image.filename": images[2].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[2].imageMimeType,
            "image.fileurl": images[2].imageFileUrl,
            "image.thumbnailurl": images[2].imageThumbnailUrl */
        },
        {
            "text": "Emily",
            "id": "emily.brown@service.org",
            "phone": "720332211",
            "url": "https://www.servicesite.com",
            "number": 9876543,
            "decimal": 98765.432,
            "dateonly": "2024-09-19",
            "datetime": "2021-05-25T09:30:15",
            "duration": 9500,
            "currency": 320000,
            "_lookup_value": guids[3],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'Emily Lookup',
            "optionset": 1,
            "optionsetcolorful": 1,
            "multiselectoptionset": null,
            "multiselectoptionsetcolorful": null,
            "multilinetext": "Emily is an HR professional handling company policies and recruitment.",
            "twooptions": true,
            "twooptionscolorful": 1,
            /* "file": guids[3],
            "file.filename": files[3].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[3].mimeType,
            "file.fileurl": files[3].fileUrl,
            'image': guids[3],
            "image.filename": images[3].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[3].imageMimeType,
            "image.fileurl": images[3].imageFileUrl,
            "image.thumbnailurl": images[3].imageThumbnailUrl */
        },
        {
            "text": "John",
            "id": "john.doe@web.com",
            "phone": "720111222",
            "url": "https://www.johndoe.com",
            "number": 1357924,
            "decimal": 753951.852,
            "dateonly": "2020-07-12",
            "datetime": "2020-07-12T16:45:00",
            "duration": 11000,
            "currency": 780000,
            "_lookup_value": guids[4],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'John Lookup',
            "optionset": 2,
            "optionsetcolorful": 2,
            "multiselectoptionset": "1,2",
            "multiselectoptionsetcolorful": "1,2",
            "multilinetext": "John is a digital marketer focusing on SEO and content strategy.",
            "twooptions": false,
            "twooptionscolorful": 0,
            /* "file": guids[4],
            "file.filename": files[4].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[4].mimeType,
            "file.fileurl": files[4].fileUrl,
            'image': guids[4],
            "image.filename": images[4].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[4].imageMimeType,
            "image.fileurl": images[4].imageFileUrl,
            "image.thumbnailurl": images[4].imageThumbnailUrl */
        },
        {
            "text": "Sophia",
            "id": "sophia.wilson@techid.com",
            "phone": "720123456",
            "url": "https://www.tech.com",
            "number": 2468135,
            "decimal": 654987.321,
            "dateonly": "2024-02-01",
            "datetime": "2024-02-01T12:00:00",
            "duration": 7000,
            "currency": 920000,
            "_lookup_value": guids[5],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'Sophia Lookup',
            "optionset": 1,
            "optionsetcolorful": 1,
            "multiselectoptionset": "1",
            "multiselectoptionsetcolorful": "1",
            "multilinetext": "Sophia is a software developer with expertise in AI and ML.",
            "twooptions": true,
            "twooptionscolorful": 1,
            /* "file": guids[5],
            "file.filename": files[5].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[5].mimeType,
            "file.fileurl": files[5].fileUrl,
            'image': guids[5],
            "image.filename": images[5].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[5].imageMimeType,
            "image.fileurl": images[5].imageFileUrl,
            "image.thumbnailurl": images[5].imageThumbnailUrl */
        },
        {
            "text": "Oliver",
            "id": "oliver.white@market.com",
            "phone": "720987654",
            "url": "https://www.marketplace.com",
            "number": 8642091,
            "decimal": 78945.632,
            "dateonly": "2024-09-28",
            "datetime": "2019-09-17T08:15:45",
            "duration": 13000,
            "currency": 670000,
            "_lookup_value": guids[6],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'Oliver Lookup',
            "optionset": 2,
            "optionsetcolorful": 2,
            "multiselectoptionset": null,
            "multiselectoptionsetcolorful": null,
            "multilinetext": "Oliver works in e-commerce and product management.",
            "twooptions": false,
            "twooptionscolorful": 0,
            /* "file": guids[6],
            "file.filename": files[6].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[6].mimeType,
            "file.fileurl": files[6].fileUrl,
            'image': guids[6],
            "image.filename": images[6].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[6].imageMimeType,
            "image.fileurl": images[6].imageFileUrl,
            "image.thumbnailurl": images[6].imageThumbnailUrl */
        },
        {
            "text": "Mia",
            "id": "mia.jones@consulting.com",
            "phone": "720654321",
            "url": "https://www.consultingfirm.com",
            "number": 3571592,
            "decimal": 45987.264,
            "dateonly": "2024-09-26",
            "datetime": "2018-12-22T11:22:33",
            "duration": 8500,
            "currency": 390000,
            "_lookup_value": guids[7],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'Mia Lookup',
            "optionset": 1,
            "optionsetcolorful": 1,
            "multiselectoptionset": "2",
            "multiselectoptionsetcolorful": "2",
            "multilinetext": "Mia is a financial analyst specializing in stock market trends.",
            "twooptions": true,
            "twooptionscolorful": 1,
            /* "file": guids[7],
            "file.filename": files[7].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[7].mimeType,
            "file.fileurl": files[7].fileUrl,
            'image': guids[7],
            "image.filename": images[7].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[7].imageMimeType,
            "image.fileurl": images[7].imageFileUrl,
            "image.thumbnailurl": images[7].imageThumbnailUrl */
        },
        {
            "text": "James",
            "id": "james.green@logistics.com",
            "phone": "720321654",
            "url": "https://www.logisticscompany.com",
            "number": 9517538,
            "decimal": 987654.987,
            "dateonly": "2017-10-30",
            "datetime": "2017-10-30T10:10:10",
            "duration": 10500,
            "currency": 720000,
            "_lookup_value": guids[8],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'James Lookup',
            "optionset": 2,
            "optionsetcolorful": 2,
            "multiselectoptionset": null,
            "multiselectoptionsetcolorful": null,
            "multilinetext": "James oversees supply chain management and warehouse logistics.",
            "twooptions": false,
            "twooptionscolorful": 0,
            /* "file": guids[8],
            "file.filename": files[8].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[8].mimeType,
            "file.fileurl": files[8].fileUrl,
            'image': guids[8],
            "image.filename": images[8].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[8].imageMimeType,
            "image.fileurl": images[8].imageFileUrl,
            "image.thumbnailurl": images[8].imageThumbnailUrl */
        },
        {
            "id": "charlotte@example.com",
            "text": "Charlotte",
            "phone": "720159357",
            "url": "https://www.agencyportal.com",
            "number": 1230987,
            "decimal": 123456.654,
            "dateonly": "2024-09-19",
            "datetime": "2016-06-14T07:45:22",
            "duration": 14000,
            "currency": 530000,
            "_lookup_value": guids[9],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'Charlotte Lookup',
            "optionset": 1,
            "optionsetcolorful": 1,
            "multiselectoptionset": "1",
            "multiselectoptionsetcolorful": "1",
            "multilinetext": "Charlotte is a creative director at a design agency.",
            "twooptions": true,
            "twooptionscolorful": 1,
            /* "file": guids[9],
            "file.filename": files[9].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[9].mimeType,
            "file.fileurl": files[9].fileUrl,
            'image': guids[9],
            "image.filename": images[9].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[9].imageMimeType,
            "image.fileurl": images[9].imageFileUrl,
            "image.thumbnailurl": images[9].imageThumbnailUrl */
        },
        {
            "text": "Liam",
            "id": "liam.brown@services.org",
            "phone": "720765432",
            "url": "https://www.servicesite.org",
            "number": 7539514,
            "decimal": 159753.123,
            "dateonly": "2015-08-21",
            "datetime": "2015-08-21T18:22:10",
            "duration": 11500,
            "currency": 890000,
            "_lookup_value": guids[10],
            '_lookup_@Microsoft.Dynamics.CRM.lookuplogicalname': 'virtualLookup',
            '_lookup_value@OData.Community.Display.V1.FormattedValue': 'Liam Lookup',
            "optionset": 2,
            "optionsetcolorful": 2,
            "multiselectoptionset": "1,2",
            "multiselectoptionsetcolorful": "1,2",
            "multilinetext": "Liam is an IT security specialist focusing on cloud safety.",
            "twooptions": false,
            "twooptionscolorful": 0,
            /* "file": guids[10],
            "file.filename": files[10].fileName,
            "file.filesizeinbytes": 902119,
            "file.mimetype": files[10].mimeType,
            "file.fileurl": files[10].fileUrl,
            'image': guids[10],
            "image.filename": images[10].imageName,
            "image.filesizeinbytes": 902119,
            "image.mimetype": images[10].imageMimeType,
            "image.fileurl": images[10].imageFileUrl,
            "image.thumbnailurl": images[10].imageThumbnailUrl */
        }
    ]
    return data;
}