import React from 'react'
import dayjs from 'dayjs'
import confetti from 'canvas-confetti'
import {
    ActionButton, Checkbox, ChoiceGroup, DefaultButton, Dropdown, FontWeights, Icon, IconButton, Label, Link, mergeStyleSets, MessageBar, MessageBarType, Panel, PanelType,
    PrimaryButton, ProgressIndicator, SearchBox, Separator, Slider, Spinner, Stack, Text, TextField, Toggle, TooltipHost,
} from '@fluentui/react'
import {
    AggregateCell, AggregationUi, createAggregationModule, createCellSelectionModule, createClientSideRowModelModule, createClipboardModule, createFilteringModule,
    createGroupingModule, createLegacyClientApiCompatibilityModule, createLicenseModule, createRowSelectionModule, createServerSideRowModelModule, createSortingModule,
    DEFAULT_COLUMN_WIDTH, FilteringUi, getTextColorForBackground, Grid, GRID_AGGREGATION_LABELS, GRID_FILTERING_LABELS, GRID_GROUPING_LABELS, GRID_LABELS,
    GRID_MODULE_PRIORITY, GRID_SORTING_LABELS, GridFilteringIconComponents, GridGroupingIconComponents, GridSortingIconComponents, GridValueRenderer, GroupCell,
    GROUP_EXPANSION_COLUMN_KEY, GroupingUi, isLightColor, LOCKED_RECORD_ROW_CLASS, NotificationCard, NotificationMessageBar, OptionSetRenderer, RECORD_LOCK_COLUMN_KEY,
    CommandBar, Form, MemoryStrategy, RECORD_SAVE_COLUMN_KEY, RowSelectionUi, ThemeGenerator, ThemeProvider, TotalCell, useGridCell, useGridColumnHeader, useGridField, useGridService, usePcfContext,
} from '@talxis/base-controls'
import { FluentProvider, Toast, ToastBody, Toaster, ToastTitle, useToastController, webLightTheme } from '@fluentui/react-components'
import { DataProvider, DataTypes, MemoryDataProvider, Operators, Type } from '@talxis/client-libraries'
import { createDealsProvider, createProductsProvider, createTicketsProvider, createTimesheetsProvider } from './data'

/** Everything a snippet may use without importing it, apart from the injected `provider`. */
export const GRID_SANDBOX_SCOPE = {
    React,
    dayjs,
    confetti,
    Grid,
    useGridService,
    useGridCell,
    useGridField,
    useGridColumnHeader,
    usePcfContext,
    Form,
    MemoryStrategy,
    FluentProvider,
    webLightTheme,
    Toaster,
    Toast,
    ToastTitle,
    ToastBody,
    useToastController,
    GRID_MODULE_PRIORITY,
    GRID_LABELS,
    GRID_SORTING_LABELS,
    GRID_FILTERING_LABELS,
    GRID_GROUPING_LABELS,
    GRID_AGGREGATION_LABELS,
    RECORD_LOCK_COLUMN_KEY,
    RECORD_SAVE_COLUMN_KEY,
    LOCKED_RECORD_ROW_CLASS,
    GROUP_EXPANSION_COLUMN_KEY,
    DEFAULT_COLUMN_WIDTH,
    createClientSideRowModelModule,
    createServerSideRowModelModule,
    createRowSelectionModule,
    createCellSelectionModule,
    createClipboardModule,
    createSortingModule,
    createFilteringModule,
    createGroupingModule,
    createAggregationModule,
    createLegacyClientApiCompatibilityModule,
    createLicenseModule,
    GridValueRenderer,
    OptionSetRenderer,
    GroupCell,
    AggregateCell,
    TotalCell,
    GroupingUi,
    AggregationUi,
    FilteringUi,
    RowSelectionUi,
    GridSortingIconComponents,
    GridFilteringIconComponents,
    GridGroupingIconComponents,
    NotificationCard,
    NotificationMessageBar,
    getTextColorForBackground,
    isLightColor,
    ThemeProvider,
    ThemeGenerator,
    createDealsProvider,
    createTimesheetsProvider,
    createTicketsProvider,
    createProductsProvider,
    DataProvider,
    MemoryDataProvider,
    DataTypes,
    Operators,
    Type,
    ActionButton,
    Checkbox,
    ChoiceGroup,
    CommandBar,
    DefaultButton,
    Dropdown,
    FontWeights,
    Icon,
    IconButton,
    Label,
    Link,
    mergeStyleSets,
    MessageBar,
    MessageBarType,
    Panel,
    PanelType,
    PrimaryButton,
    ProgressIndicator,
    SearchBox,
    Separator,
    Slider,
    Spinner,
    Stack,
    Text,
    TextField,
    Toggle,
    TooltipHost,
}
