name: Build and Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      # Ensure npm 11.5.1 or later is installed - https://docs.npmjs.com/trusted-publishers#github-actions-configuration
      - name: Update npm
        run: npm install -g npm@latest
      - name: Output NPM version
        run: npm --version
      - name: Set package.json version from release tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          npm version --no-git-tag-version "$VERSION"
        env:
          GITHUB_REF: ${{ github.ref }}
      - run: npm install
      - run: npm run build
      - run: npm publish --access-public
